name: Build and Sign

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'The source branch or ref to build from'
        default: 'main'
        required: true

      release_name:
        description: 'The name for the release'
        required: true


env:
  SOURCE_REPOSITORY: 'danstis/rmstale'
  SOURCE_REPOSITORY_NAME: 'rmstale'


jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 1

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
        id: go

      - name: Build application
        shell: bash
        run: |
          GOARCH=amd64 go build -o -s -w -X main.AppVersion==${{ github.event.inputs.release_name }} -o rmstale-amd64.exe ./rmstale.go
          GOARCH=arm64 go build -o -s -w -X main.AppVersion==${{ github.event.inputs.release_name }} -o rmstale-arm64.exe ./rmstale.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-to-sign
          path: |
            rmstale-amd64.exe
            rmstale-arm64.exe

  sign:
    environment: OSSign
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: files-to-sign
      

      - uses: ossign/ossign@main
        with:
          config: ${{ secrets.OSSIGN_CONFIG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          installOnly: false
          inputFiles: |
            rmstale-amd64.exe
            rmstale-arm64.exe
          fileType: pecoff


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rmstale-amd64.exe
            rmstale-arm64.exe
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.run_id }}
          body: |
            <img src="https://github.com/ossign.png" alt="OSSign Logo" width="100" height="100" />
            # Signed Release ${{ github.event.inputs.release_name }}
            
            These are the distributable files for the signed release of ${{ env.SOURCE_REPOSITORY_NAME }} ${{ github.event.inputs.release_name }}

            The source code was fetched from https://github.com/${{ env.SOURCE_REPOSITORY }}@${{ github.event.inputs.source_branch }}
            
          


